return {
	BotKiller = {
		[1] = {
			Title = "Bot Killa I",
			Description = "Kill 10 people (including NPCS)",
			Reward = "Cash",
			RewardValue = 100,
			QuestType = "Kill",
			QuestRequirement = 10,
		},
		[2] = {
			Title = "Bot Killa II",
			Description = "Kill 20 people (including NPCS)",
			Reward = "Cash",
			RewardValue = 250,
			QuestType = "Kill",
			QuestRequirement = 20,
		},
		[3] = {
			Title = "Bot Killa III",
			Description = "Kill 30 people (including NPCS)",
			Reward = "Cash",
			RewardValue = 500,
			QuestType = "Kill",
			QuestRequirement = 30,
		},
		[4] = {
			Title = "Bot Killa IV",
			Description = "Kill 40 people (including NPCS)",
			Reward = "Cash",
			RewardValue = 1000,
			QuestType = "Kill",
			QuestRequirement = 40,
		},
	},
}
