return {
	BotKiller1 = {
		Title = "Bot Killa I",
		Description = "Kill 10 people (including NPCS)",
		Reward = "Cash",
		RewardValue = 100,
		QuestRequirement = 10,
	},
	BotKiller2 = {
		Title = "Bot Killa II",
		Description = "Kill 20 people (including NPCS)",
		Reward = "Cash",
		RewardValue = 250,
		QuestRequirement = 20,
	},
	BotKiller3 = {
		Title = "Bot Killa III",
		Description = "Kill 30 people (including NPCS)",
		Reward = "Cash",
		RewardValue = 500,
		QuestRequirement = 30,
	},
	BotKiller4 = {
		Title = "Bot Killa IV",
		Description = "Kill 40 people (including NPCS)",
		Reward = "Cash",
		RewardValue = 1000,
		QuestRequirement = 40,
	},
}
