local LimbsEnum = {
	Head = 1,
	UpperTorso = 2,
	LowerTorso = 3,

	LeftUpperArm = 4,
	LeftLowerArm = 5,
	LeftHand = 6,
	RightUpperArm = 7,
	RightLowerArm = 8,
	RightHand = 9,

	LeftUpperLeg = 10,
	LeftLowerLeg = 11,
	LeftFoot = 12,
	RightUpperLeg = 13,
	RightLowerLeg = 14,
	RightFoot = 15,

	[1] = "Head",
	[2] = "UpperTorso",
	[3] = "LowerTorso",

	[4] = "LeftUpperArm",
	[5] = "LeftLowerArm",
	[6] = "LeftHand",
	[7] = "RightUpperArm",
	[8] = "RightLowerArm",
	[9] = "RightHand",

	[10] = "LeftUpperLeg",
	[11] = "LeftLowerLeg",
	[12] = "LeftFoot",
	[13] = "RightUpperLeg",
	[14] = "RightLowerLeg",
	[15] = "RightFoot",
}

return LimbsEnum
