return {
	Buffalo = {
		Health = 200,
		AttackRunSpeed = 100,
	},

	-- Horses
	LeBangAverage = {
		Health = 100,
		MaxForwardSpeed = 40,
		MaxReverseSpeed = 10,
		Acceleration = 20,
		Deceleration = 20,
	},
	Middlemanston = {
		Health = 175,
		MaxForwardSpeed = 60,
		MaxReverseSpeed = 10,
		Acceleration = 30,
		Deceleration = 30,
	},
	RoidiedUppie = {
		Health = 70,
		MaxForwardSpeed = 100,
		MaxReverseSpeed = 50,
		Acceleration = 10,
		Deceleration = 5,
	},
	Chonkie = {
		Health = 300,
		MaxForwardSpeed = 25,
		MaxReverseSpeed = 10,
		Acceleration = 10,
		Deceleration = 10,
	},
	PrimeTime = {
		Health = 200,
		MaxForwardSpeed = 70,
		MaxReverseSpeed = 35,
		Acceleration = 40,
		Deceleration = 40,
	},
}
